version: "3.4"

services:
  app:
    container_name: go-todo-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    tty: true
    volumes:
      - .:/go/src/app
    depends_on:
      - "mysql"
  mysql:
    container_name: go-todo-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-app
      MYSQL_USER: todo-app
      MYSQL_PASSWORD: todo-app
      TZ: "Asia/Tokyo"
    volumes:
      - "./tmp/mysql:/var/lib/mysql"
      - "./db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./db/sql:/docker-entrypoint-initdb.d"
